### ISSUE TITLE
unknown LayoutType "0"

### ISSUE THREAD

**Issue by thalesgaldino** [manicantic/react-native-navigation-redux-integration#2]
When I try to dispatch:

```
dispatch(setStackRoot([
  { 
    component: {
      name: 'CustomName'
    } 
  },
]))
```

My index:

```
Navigation.setRoot({
    root: {
      component: {
        name: ROOT_SCREEN,
      },
    },
  });
```

### Environment
* react-native-navigation-redux-integration: 0.3.4
* React Native Navigation version: 2.1.3
* React Native version: 0.57.4
* Platform(s) (iOS, Android, or both?): Android at least
* Device info (Simulator/Device? OS version? Debug/Release?): Debug

**Comment by manicantic** [comment]
Hi @thalesgaldino . You can not set stack root on component, you will need to set root with stack. 
 https://wix.github.io/react-native-navigation/#/docs/screen-api?id=setstackrootcomponentid-params

**Comment by thalesgaldino** [comment]
thanks for getting back to it @manicantic . I had to pause this change, and only now, Im back to this. Just checking if I understood. Currently, in my code, I use `Navigation.setRoot`. Do you mean that I'll need to replace that for `Navigation.setStackRoot`?

**Comment by manicantic** [comment]
Hi @thalesgaldino . In order to user setStackRoot you need to set stack layout in setRoot ( https://wix.github.io/react-native-navigation/#/docs/layout-types?id=stack-based-app-with-options-example-initialised-with-2-screens ). Then when you have stack as your layout you can use setStackRoot. This error you got is react-native-navigation error because you are trying to set stack root on layout which isn't stack.
